package system

import (
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// Webmail integration serves a shared Roundcube installation at
// webmail.<domain> for every domain the operator opts in. Roundcube itself is
// installed (and pointed at the local Dovecot/Postfix) by the installer; the
// panel only generates a single nginx vhost listing the enabled hostnames and
// rebuilds it from database state, the same regenerate-from-state model used
// for mail maps and DKIM tables.

// webmailRoots are the document roots Debian/Ubuntu's roundcube packages use,
// most specific first. The first one that exists wins.
var webmailRoots = []string{
	"/var/lib/roundcube/public_html",
	"/var/lib/roundcube",
	"/usr/share/roundcube",
}

// WebmailRoot returns the Roundcube document root if it is installed, else "".
func WebmailRoot() string {
	for _, root := range webmailRoots {
		if _, err := os.Stat(filepath.Join(root, "index.php")); err == nil {
			return root
		}
	}
	return ""
}

// HaveWebmail reports whether a Roundcube installation is present.
func HaveWebmail() bool { return WebmailRoot() != "" }

// DefaultPHPSocket returns the system PHP-FPM pool socket (the default www
// pool, distinct from the per-domain pools the panel creates). Roundcube runs
// in this shared pool as www-data.
func DefaultPHPSocket() string {
	versions := PHPVersions()
	ver := versions[len(versions)-1]
	return "/run/php/php" + ver + "-fpm.sock"
}

// WebmailHost is one opted-in domain: its name, the parent domain's document
// root (which answers the webmail.<domain> ACME challenge), and the certificate
// securing webmail.<domain> when one is available (else served over HTTP only).
type WebmailHost struct {
	Domain   string
	DocRoot  string
	CertPath string
	KeyPath  string
}

// One server block per enabled domain so each webmail.<domain> can present its
// own certificate. The :80 block always serves the ACME HTTP-01 challenge from
// the parent domain's docroot (so the cert that covers webmail.<domain> can be
// issued alongside the domain's); with a certificate it redirects to HTTPS,
// otherwise it serves Roundcube directly.
var webmailVhostTemplate = template.Must(template.New("webmail").Parse(`# Managed by RePanel — webmail (Roundcube). Regenerated from panel state.
{{- $root := .Root}}{{- $php := .PHPSock}}
{{- range .Hosts}}
server {
    listen 80;
    listen [::]:80;
    server_name webmail.{{.Domain}};

    location /.well-known/acme-challenge/ { root {{.DocRoot}}; }
{{- if .CertPath}}
    location / { return 301 https://$host$request_uri; }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name webmail.{{.Domain}};

    ssl_certificate     {{.CertPath}};
    ssl_certificate_key {{.KeyPath}};
{{- end}}

    root {{$root}};
    index index.php;

    access_log /var/log/nginx/webmail.access.log;
    error_log  /var/log/nginx/webmail.error.log;

    client_max_body_size 64m;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Roundcube internals that must never be served.
    location ~ ^/(config|temp|logs|bin|SQL|installer)/ { deny all; }
    location ~ /\.(?!well-known) { deny all; }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass unix:{{$php}};
    }
}
{{- end}}
`))

type webmailVhostData struct {
	Root    string
	PHPSock string
	Hosts   []WebmailHost
}

// The webmail vhost is regenerated by WebServer.RebuildWebmail (webserver.go),
// which writes it to whichever server fronts the stack (nginx or Apache).

// renderWebmailVhost renders one webmail server block per enabled domain.
func renderWebmailVhost(root, phpSock string, hosts []WebmailHost) (string, error) {
	var sb strings.Builder
	err := webmailVhostTemplate.Execute(&sb, webmailVhostData{
		Root:    root,
		PHPSock: phpSock,
		Hosts:   hosts,
	})
	return sb.String(), err
}
