package system

import (
	"archive/tar"
	"compress/gzip"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// wordpressURL is the canonical "latest release" tarball.
const wordpressURL = "https://wordpress.org/latest.tar.gz"

// WordPressOptions describes a one-click WordPress install into a domain's
// document root. WordPress requires MariaDB/MySQL; the database must already
// exist (the API layer creates it before calling Install).
type WordPressOptions struct {
	DocRoot    string
	SysUser    string
	SiteURL    string
	Title      string
	AdminUser  string
	AdminPass  string
	AdminEmail string
	DBName     string
	DBUser     string
	DBPass     string
}

// InstallWordPress downloads WordPress core, extracts it into DocRoot, writes a
// ready-to-use wp-config.php and hands ownership to the site's system user. If
// the WP-CLI binary (`wp`) is available it also completes the install (creating
// the admin account); autoConfigured reports whether that happened. When it is
// false, the operator finishes the short browser-based setup wizard.
func InstallWordPress(opts WordPressOptions) (autoConfigured bool, err error) {
	if err := downloadAndExtractWordPress(opts.DocRoot); err != nil {
		return false, err
	}
	if err := writeWPConfig(opts); err != nil {
		return false, err
	}
	if Linux() && validSysName.MatchString(opts.SysUser) {
		if _, err := run("chown", "-R", opts.SysUser+":"+opts.SysUser, opts.DocRoot); err != nil {
			return false, fmt.Errorf("chown docroot: %w", err)
		}
	}
	return finishWordPressInstall(opts), nil
}

func downloadAndExtractWordPress(docRoot string) error {
	if err := os.MkdirAll(docRoot, 0o755); err != nil {
		return err
	}
	// A placeholder index.html would otherwise shadow nothing but is noise.
	os.Remove(filepath.Join(docRoot, "index.html"))

	client := &http.Client{Timeout: 5 * time.Minute}
	resp, err := client.Get(wordpressURL)
	if err != nil {
		return fmt.Errorf("download WordPress: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("download WordPress: unexpected status %s", resp.Status)
	}
	return extractWordPress(resp.Body, docRoot)
}

// extractWordPress unpacks the WordPress tar.gz, stripping the leading
// "wordpress/" directory so files land directly in dest. It refuses any entry
// that would escape dest.
func extractWordPress(r io.Reader, dest string) error {
	gz, err := gzip.NewReader(r)
	if err != nil {
		return err
	}
	defer gz.Close()
	tr := tar.NewReader(gz)
	cleanDest := filepath.Clean(dest)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return err
		}
		if !strings.HasPrefix(hdr.Name, "wordpress/") {
			continue // ignore anything outside the wordpress/ root
		}
		name := strings.TrimPrefix(hdr.Name, "wordpress/")
		if name == "" {
			continue
		}
		target := filepath.Join(dest, name)
		if rel, err := filepath.Rel(cleanDest, target); err != nil || strings.HasPrefix(rel, "..") {
			return fmt.Errorf("unsafe path in archive: %s", hdr.Name)
		}
		switch hdr.Typeflag {
		case tar.TypeDir:
			if err := os.MkdirAll(target, 0o755); err != nil {
				return err
			}
		case tar.TypeReg:
			if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
				return err
			}
			f, err := os.OpenFile(target, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o644)
			if err != nil {
				return err
			}
			if _, err := io.Copy(f, tr); err != nil { //nolint:gosec // bounded by WP core size
				f.Close()
				return err
			}
			f.Close()
		}
	}
}

// writeWPConfig renders wp-config.php with the database credentials and a fresh
// set of authentication salts.
func writeWPConfig(opts WordPressOptions) error {
	salts, err := wordpressSalts()
	if err != nil {
		return err
	}
	cfg := fmt.Sprintf(`<?php
/* Generated by RePanel. */
define( 'DB_NAME', '%s' );
define( 'DB_USER', '%s' );
define( 'DB_PASSWORD', '%s' );
define( 'DB_HOST', 'localhost' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

%s

$table_prefix = 'wp_';

define( 'WP_DEBUG', false );

if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}
require_once ABSPATH . 'wp-settings.php';
`, phpEscape(opts.DBName), phpEscape(opts.DBUser), phpEscape(opts.DBPass), salts)

	return os.WriteFile(filepath.Join(opts.DocRoot, "wp-config.php"), []byte(cfg), 0o640)
}

// wordpressSalts returns the eight define() lines WordPress expects, generated
// locally so the install needs no second network round-trip.
func wordpressSalts() (string, error) {
	keys := []string{"AUTH_KEY", "SECURE_AUTH_KEY", "LOGGED_IN_KEY", "NONCE_KEY",
		"AUTH_SALT", "SECURE_AUTH_SALT", "LOGGED_IN_SALT", "NONCE_SALT"}
	var b strings.Builder
	for _, k := range keys {
		salt, err := randomSalt()
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "define( '%s', '%s' );\n", k, salt)
	}
	return b.String(), nil
}

// randomSalt returns a 64-character hex secret.
func randomSalt() (string, error) {
	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf), nil
}

// phpEscape escapes a value for a single-quoted PHP string literal.
func phpEscape(v string) string {
	return strings.NewReplacer(`\`, `\\`, `'`, `\'`).Replace(v)
}

// finishWordPressInstall runs `wp core install` as the site's system user when
// WP-CLI is available, creating the admin account. Returns true on success.
func finishWordPressInstall(opts WordPressOptions) bool {
	if !Linux() || !have("wp") || opts.AdminUser == "" {
		return false
	}
	_, err := run("sudo", "-n", "-u", opts.SysUser, "--", "wp",
		"--path="+opts.DocRoot, "core", "install",
		"--url="+opts.SiteURL,
		"--title="+opts.Title,
		"--admin_user="+opts.AdminUser,
		"--admin_password="+opts.AdminPass,
		"--admin_email="+opts.AdminEmail,
		"--skip-email")
	return err == nil
}
